// f_flat Grammar 2022
// 
// Parser Class Definition File

// SHELL GENERATED BY PARSERGEN VERSION 5.0.4

#ifndef PARSER
#define PARSER

#include <string>
using namespace std;

#include "FScan.h" // scanner class definition

#include "FCodeGen.h" // code generator class definition

class Parser
{
public:

	Parser();

	void SystemGoal();

private:

	Token savedToken;
	bool  tokenAvailable;

	void SyntaxError(Token t, string msg);

	Token NextToken();

	void Match(Token t);

	void VarDec();

	void VarDecList();

	void VarDecListTail();

	void VarDecTail();

	void DecTail();

	void Type();

	void Literal();

	void MultOp();

	void FactorTail();

	void Primary(ExprRec& result);

	void AddOp(OpRec& op);

	void ExprTail();

	void Factor();

	void RelOp();

	void RelTail();

	void Relational();

	void AndTail();

	void Negation();

	void CondTail();

	void AndCond();

	void VarInit();

	void FelseClause();

	void Condition();

	void ForStmt();

	void DoFwhileStmt();

	void WhileStmt();

	void FifStmt();

	void ItemListTail();

	void ItemList();

	void VariableTail();

	void VarListTail();

	void VarList();

	void Expression(ExprRec& result);
	//void Expression();

	void Variable();

	void FoutlnStmt();

	void FoutStmt();

	void FinStmt();

	void AssignStmt();

	void Declaration();

	void StructStmt();

	void SimpleStmt();

	void StmtTail();

	void Statement();

	void StmtList();

	void Program();

}; // end of Parser class

#endif
